### ISSUE TITLE
[Feature Request] World History and Player History

### ISSUE THREAD

**Issue by Nin2648** [DubyaDude/RubyClientPublic#153] opened 2021-02-23 17:49 UTC
- An ability to see all of the recent instances you have previously been in, with the choice of rejoining / dropping a portal to that instance.
- An ability to see all of the recent players you have been in (perhaps organized by the instance, to track larger numbers of players) with the option to view them in social menu. 
- ^ Options to add, block, mute these players
- Perhaps able to see thumbnail of avatar they last had for easier identification

**Comment by DubyaDude** [comment] 2021-02-23 18:40
Duplicate of #41 for 'recently seen users' and world history is on the [Trello ](https://trello.com/c/rK93iBiU/16-worlds-world-history)

**Closed by DubyaDude** 2021-02-23 18:40 UTC
