### ISSUE TITLE
[Feature Request] Third Person / Free View Camera

### ISSUE THREAD

**Issue by Nin2648** [DubyaDude/RubyClientPublic#149] opened 2021-02-23 17:34 UTC
Pretty self-explanatory - It would be nice to be able to go into 3rd person mode, and have more control over camera and view position while in desktop mode. For VR, maybe camera manipulation like zoom etc could be implemented as well.

**Comment by DubyaDude** [comment] 2021-02-23 18:21
Duplicate of #120 and #65

**Closed by DubyaDude** 2021-02-23 18:21 UTC
