### ISSUE TITLE
Something for beta

### ISSUE THREAD

**Issue by katzina00** [DubyaDude/RubyClientPublic#137] opened 2021-01-25 11:53 UTC
Make it so that you can search for avatars. Like if u search rainbow. U get avatars with rainbow name or something. Or if u search NSFW u get avatars with NSFW. Stuff like that could be usefull.

**Comment by Murkur** [comment] 2021-01-25 12:30
avatar searching is not as simple as it sounds it requires an avatar database, dubbya acquired a database over a year ago but will take some time to implement.

**Comment by DubyaDude** [comment] 2021-01-25 18:01
Duplicate of https://github.com/DubyaDude/RubyClientPublic/issues/31

**Closed by DubyaDude** 2021-01-25 18:01 UTC
