### ISSUE TITLE
Additional Social Favorite Lists 

### ISSUE THREAD

**Issue by MukamiMuki** [DubyaDude/RubyClientPublic#114] opened 2020-10-05 05:31 UTC
if possible something similar to the avatar favorite list, but with players so i can sort / make more groups of people

**Comment by DubyaDude** [comment] 2021-01-02 16:43
Duplicate of https://github.com/DubyaDude/RubyClientPublic/issues/100

**Closed by DubyaDude** 2021-01-02 16:43 UTC
Labels: type:duplicate, type:suggestion
