### ISSUE TITLE
Clear Notifications

### ISSUE THREAD

**Issue by Murkur** [DubyaDude/RubyClientPublic#116] opened 2020-10-09 21:56 UTC
Oh no your at a drinking party and your fps is 10 and you have thousands of old invites you cant see because the menu doesnt update thanks to low FPS|

TLDR add a button to the settings that allows clearing of your hud notifications like invites and friend requests

**Comment by KuwuroUsagi** [comment] 2020-10-13 09:27
oh yeah I had something similar to this suggested back in the day, it'd still be a super nice QOL addition
![dgWavoP](https://user-images.githubusercontent.com/6632311/95842578-8d302780-0cfb-11eb-9d01-ab3d4a46bd16.png)

**Comment by DubyaDude** [comment] 2021-01-02 16:34
Duplicate of https://github.com/DubyaDude/RubyClientPublic/issues/11

**Closed by DubyaDude** 2021-01-02 16:34 UTC
Labels: type:duplicate, type:suggestion
